### ISSUE TITLE
Ajouter une licence (permissive :))

### ISSUE THREAD

**Issue by davidbgk** [makinacorpus/iframe-loader#4]
Je vais peut-être m'en inspirer pour https://github.com/etalab/udata/issues/268 mais ça requiert une licence me permettant de le faire.

**Comment by mabhub** [comment]
Est-ce que si on y met un MIT ça te conviendrait ? :)

**Comment by davidbgk** [comment]
Oui nickel, c'est compatible avec l'AGPL que l'on utilise sur le projet. Merci :)

**Comment by mabhub** [comment]
Ça doit être bon à partir fe20dd82206735dbc0ed9760a248018b14e2b19f !
